# KAI Data Center Builder 2.2
# Release Date 2026-02-20
# Docker Compose - Default File

services:
  dse:
    image: ${DSE_DOCKER_IMAGE}
    command: --accept_eula --server_name ${SERVER_NAME} --user_name ${USER} --db_name ${DB_NAME} ${DATA_URL} ${LICENSE_SERVERS} ${FEATURES} ${PLUGINS}
    ports:
      - ${WEBUI}:443
      - ${GRPC}:50001
    restart: always
    volumes:
        - ${STORAGE}:/var/lib/dse
